workflow:
  rules:
    - if: "$CI_MERGE_REQUEST_IID"
    - if: "$CI_COMMIT_TAG"
stages:
  - merge

merge_request:
  stage: merge    
  variables:
    name: rahul

  script:
    - echo $name
    - echo "$pipeline triggred this child when $event event is created"
    - date
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_COMMIT_TAG
    - echo $CI_COMMIT_BRANCH
    - echo "$CI_MERGE_REQUEST_IID Merge Request created from \"$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME\" branch ---> \"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME\" branch"
