stages:
  - artifacts
  - parent

## This job will generate artifacts and will send to artifact-to-child.yaml child pipeline
artifacts:
  stage: artifacts
  variables:
    key1: value1
    key2: value2
  artifacts:
    paths: 
      - ./artifacts.txt
  script:
    - echo "Generated Artifacts" > artifacts.txt

## This pipeline will only trigger when a MR 
## is created.
merge_request_pipeline:
  stage: parent
  variables: 
    pipeline: parent
    event: $CI_PIPELINE_SOURCE
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: "$CI_MERGE_REQUEST_IID"
    - if: "$CI_COMMIT_TAG"
  trigger:
    include: .gitlab/workflows/merge-request-pipeline.yaml

    ## trigger:strategy to force the trigger job to wait for the downstream pipeline to complete before it is marked as success.
    strategy: depend

## This job will run triggers a child which downloads artifacts generate in previous jobs.
artifact-to-child:
  stage: parent
  variables:
    ## Needs: to make child download parent artifacts. ID of parent pipeline needs to pass.
    PARENT_PIPELINE_ID: $CI_PIPELINE_ID
  trigger:
    include: .gitlab/workflows/artifact-to-child.yaml
    strategy: depend

## This job will trigger a child only when changes are made in particular directory
build_app:
  stage: parent
  rules:
    - changes:
        - app/**/*
  trigger:
    include: .gitlab/workflows/build_app.yaml
    strategy: depend
